---
- name: Install Docker
  hosts: all
  become: true
  tasks:
    - name: role geerlingguy.docker
      when: ansible_facts['lsb']['release'] >= "18.04"
      include_role:
        name: geerlingguy.docker
