---
- name: Install Docker
  hosts: all
  become: true
  vars:
    vm_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  tasks:
    - name: role geerlingguy.docker
      when: ansible_facts['lsb']['release'] >= "18.04"
      include_role:
        name: geerlingguy.docker

    - name: install dependencies
      apt:
        name: python3-pip
        update_cache: true

    - name: install dependencies
      pip:
        name: docker

    - name: create directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /srv/gitlab/config
        - /srv/gitlab/data
        - /srv/gitlab/logs

    - name: start gitlab
      docker_container:
        name: gitlab
        hostname: gitlab.example.com
        state: started
        restart: yes
        restart_policy: always
        env:
          GITLAB_OMNIBUS_CONFIG: "external_url 'http://{{ vm_ip }}'"
        ports:
          - "80:80"
          - "443:443"
          - "2222:22"
        volumes:
          - /srv/gitlab/config:/etc/gitlab
          - /srv/gitlab/logs:/var/log/gitlab
          - /srv/gitlab/data:/var/opt/gitlab
        image: gitlab/gitlab-ce:latest

    - name: start gitlab-runner
      docker_container:
        name: gitlab-runner
        state: started
        restart: yes
        restart_policy: always
        volumes:
          - /srv/gitlab-runner/config:/etc/gitlab-runner
          - /var/run/docker.sock:/var/run/docker.sock
        image: gitlab/gitlab-runner:latest
